### ISSUE TITLE
Start DLAS.cmd file pops up and closes

### ISSUE THREAD

**Issue by teachtaha** [FurkanGozukara/Stable-Diffusion#1]
Please guide! my Start DLAS.cmd file pops up and closes w/o any dependency error. However, Setup DLAS.bat file is working fine

**Comment by FurkanGozukara** [comment]
it is probably related to your installation
have you fixed it?

**Comment by teachtaha** [comment]
Yes sir! I opened the cmd file through notebook and uncommented the cmd:k.
The file then showed errors and I resolved those dependencies.
