### ISSUE TITLE
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\deepface\roop\venv\lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by gmf1982** [FurkanGozukara/Stable-Diffusion#10]
Please help, I have this problem：

(venv) D:\deepface\roop>python run.py --keep-frames --keep-fps --gpu-vendor nvidia
Traceback (most recent call last):
  File "D:\deepface\roop\run.py", line 3, in <module>
    from roop import core
  File "D:\deepface\roop\roop\core.py", line 14, in <module>
    import torch
  File "D:\deepface\roop\venv\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\deepface\roop\venv\lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.

**Comment by FurkanGozukara** [comment]
I would do a fresh install
Looks like at some point of installation download or installing a lib was failed

I am doing a fresh installation on my pc to test latest commit of roop
