### ISSUE TITLE
can not change enviromnet variable

### ISSUE THREAD

**Issue by Divitjal** [FurkanGozukara/Stable-Diffusion#12]
can change the enviromnet variable, it is not coming as an option pls help 

![Screenshot (3)](https://github.com/FurkanGozukara/Stable-Diffusion/assets/123242491/68ccfe2f-1863-45ec-bcb0-23776fea3984)
![Screenshot (4)](https://github.com/FurkanGozukara/Stable-Diffusion/assets/123242491/06f12cd7-bac2-4b5d-b1d9-07c13e761bcb)
![Screenshot (5)](https://github.com/FurkanGozukara/Stable-Diffusion/assets/123242491/2311e9eb-0895-43f5-900c-6fc9843c4d5c)

can someone pls help and tell me what to do

**Comment by FurkanGozukara** [comment]
click new and add new one

**Comment by Divitjal** [comment]
> click new and add new one

still not working

**Comment by FurkanGozukara** [comment]
> > click new and add new one
> 
> still not working

then it is related to your windows installation - maybe you have virus? not have administrator rights? 

if you are my patreon supporter i can connect your pc and try to install
