### ISSUE TITLE
this problem has been troubling me since this week have there been any new update

### ISSUE THREAD

**Issue by nanaj96** [FurkanGozukara/Stable-Diffusion#13]
2023-06-10 20:20:37.394766: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/kohya_ss/train_network.py:17 in <module>                                                   │
│                                                                                                  │
│    14 from accelerate.utils import set_seed                                                      │
│    15 from diffusers import DDPMScheduler                                                        │
│    16                                                                                            │
│ ❱  17 import library.train_util as train_util                                                    │
│    18 from library.train_util import (                                                           │
│    19 │   DreamBoothDataset,                                                                     │
│    20 )                                                                                          │
│                                                                                                  │
│ /home/kohya_ss/library/train_util.py:56 in <module>                                              │
│                                                                                                  │
│     53 │   KDPM2AncestralDiscreteScheduler,                                                      │
│     54 )                                                                                         │
│     55 from huggingface_hub import hf_hub_download                                               │
│ ❱   56 import albumentations as albu                                                             │
│     57 import numpy as np                                                                        │
│     58 from PIL import Image                                                                     │
│     59 import cv2                                                                                │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/albumentations/__init__.py:5 in <module>        │
│                                                                                                  │
│    2                                                                                             │
│    3 __version__ = "1.3.0"                                                                       │
│    4                                                                                             │
│ ❱  5 from .augmentations import *                                                                │
│    6 from .core.composition import *                                                             │
│    7 from .core.serialization import *                                                           │
│    8 from .core.transforms_interface import *                                                    │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/__init__.py:2 in   │
│ <module>                                                                                         │
│                                                                                                  │
│    1 # Common classes                                                                            │
│ ❱  2 from .blur.functional import *                                                              │
│    3 from .blur.transforms import *                                                              │
│    4 from .crops.functional import *                                                             │
│    5 from .crops.transforms import *                                                             │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/__init__.py:1 │
│ in <module>                                                                                      │
│                                                                                                  │
│ ❱ 1 from .functional import *                                                                    │
│   2 from .transforms import *                                                                    │
│   3                                                                                              │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/functional.py │
│ :5 in <module>                                                                                   │
│                                                                                                  │
│     2 from math import ceil                                                                      │
│     3 from typing import Sequence, Union                                                         │
│     4                                                                                            │
│ ❱   5 import cv2                                                                                 │
│     6 import numpy as np                                                                         │
│     7                                                                                            │
│     8 from albumentations.augmentations.functional import convolve                               │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py:181 in <module>                 │
│                                                                                                  │
│   178 │   if DEBUG: print('OpenCV loader: DONE')                                                 │
│   179                                                                                            │
│   180                                                                                            │
│ ❱ 181 bootstrap()                                                                                │
│   182                                                                                            │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py:153 in bootstrap                │
│                                                                                                  │
│   150 │                                                                                          │
│   151 │   py_module = sys.modules.pop("cv2")                                                     │
│   152 │                                                                                          │
│ ❱ 153 │   native_module = importlib.import_module("cv2")                                         │
│   154 │                                                                                          │
│   155 │   sys.modules["cv2"] = py_module                                                         │
│   156 │   setattr(py_module, "_native", native_module)                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/importlib/__init__.py:126 in import_module                             │
│                                                                                                  │
│   123 │   │   │   if character != '.':                                                           │
│   124 │   │   │   │   break                                                                      │
│   125 │   │   │   level += 1                                                                     │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   127                                                                                            │
│   128                                                                                            │
│   129 _RELOADING = {}                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/kohya_ss/venv/bin/accelerate:8 in <module>                                                 │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py:45 in     │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py:918 in            │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py:580 in            │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/home/kohya_ss/venv/bin/python', 'train_network.py', '--enable_bucket', 
'--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/home/chimu/img', 
'--reg_data_dir=/home/chimu/reg', '--resolution=768,768', '--output_dir=/home/chimu/model', '--logging_dir=/home/chimu/log', 
'--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', 
'--unet_lr=0.0001', '--network_dim=128', '--output_name=test1', '--lr_scheduler_num_cycles=10', '--learning_rate=0.0001', 
'--lr_scheduler=cosine', '--train_batch_size=1', '--max_train_steps=30400', '--save_every_n_epochs=1', '--mixed_precision=fp16',
'--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', 
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status

**Comment by FurkanGozukara** [comment]
looks like installation error

probably you failed to install  redistributable
Download and install Visual Studio 2015, 2017, 2019, and 2022 redistributable
https://aka.ms/vs/17/release/vc_redist.x64.exe

i would reinstall from scratch 
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
