### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by ColorQuing** [FurkanGozukara/Stable-Diffusion#17]
Hi,FurkanGozukara, I'm big fan of your YT channel and subscriber
above all I can't Thank you enough for creating this app. 

but i can't run this app because If I type that  "python run.py --keep-frames --keep-fps --max-cores 1" or "python run.py --keep-frames --keep-fps --gpu-vendor nvidia"

I got a message this that :" AttributeError: module 'tensorflow' has no attribute 'keras'"

so did it that "pip install --upgrade pip" and "pip install tensorflow==2.12.*"

but it didn't work, so even i did that" Step 7:Activate venv once again" but it didn't work too

<img width="727" alt="스크린샷 2023-06-18 195838" src="https://github.com/FurkanGozukara/Stable-Diffusion/assets/136964674/95581eb0-f5a1-4a5c-815c-de7365a351d1">

How can i fix this sir? 

<img width="720" alt="스크린샷 2023-06-18 195011" src="https://github.com/FurkanGozukara/Stable-Diffusion/assets/136964674/122d785c-5afb-4e22-8897-89ad1fae4995">

If i see your reply I would really appreciate that.

**Comment by FurkanGozukara** [comment]
I see they still dşidnt update https://github.com/s0md3v/roop so it should work

what python do you use what version?

**Comment by ColorQuing** [comment]
> I see they still didnt update https://github.com/s0md3v/roop so it should work
> 
> what python do you use what version?

I'm Using Version of 3.10.9 
What should I do to solve this problem sir? 
I'm really dying to play this app 



<img width="289" alt="스크린샷 2023-06-18 230455" src="https://github.com/FurkanGozukara/Stable-Diffusion/assets/136964674/545e5d9d-c2f9-4b46-9825-2719a1f5b82b">

**Comment by FurkanGozukara** [comment]
> > I see they still didnt update https://github.com/s0md3v/roop so it should work
> > what python do you use what version?
> 
> I'm Using Version of 3.10.9 What should I do to solve this problem sir? I'm really dying to play this app
> 
> <img alt="스크린샷 2023-06-18 230455" width="289" src="https://user-images.githubusercontent.com/136964674/246670088-545e5d9d-c2f9-4b46-9825-2719a1f5b82b.png">

they did update today
did you try a fresh install?

**Comment by ColorQuing** [comment]
I received a mail that you closed the Issue, I'm sorry I was too busy from
personal life, and I had searched another way to solve this problem. but
failed. so I decided just to leave it. I think someday the day your amazing
Roop App would use. Thanks for your kindness and helping.
