### ISSUE TITLE
customkinter..please help me with this

### ISSUE THREAD

**Issue by 6xoxo9** [FurkanGozukara/Stable-Diffusion#19]
(venv) D:\deepfake\roop>python run.py --keep-frames --keep-fps --execution-provider cuda
Traceback (most recent call last):
  File "D:\deepfake\roop\run.py", line 3, in <module>
    from roop import core
  File "D:\deepfake\roop\roop\core.py", line 22, in <module>
    import roop.ui as ui
  File "D:\deepfake\roop\roop\ui.py", line 3, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'

**Comment by FurkanGozukara** [comment]
> (venv) D:\deepfake\roop>python run.py --keep-frames --keep-fps --execution-provider cuda Traceback (most recent call last): File "D:\deepfake\roop\run.py", line 3, in from roop import core File "D:\deepfake\roop\roop\core.py", line 22, in import roop.ui as ui File "D:\deepfake\roop\roop\ui.py", line 3, in import customtkinter as ctk ModuleNotFoundError: No module named 'customtkinter'

Are you on Windows? Which  python? Did you try with installing c drive?

**Comment by 6xoxo9** [comment]
yes i am using windows, python 3.11, the NVIDIA named file is installed in c drive(CUDNN) AND the one you said we can create in any other folder with the name deepface so I did the exact but I am facing this problem..

**Comment by FurkanGozukara** [comment]
> yes i am using windows, python 3.11, the NVIDIA named file is installed in c drive(CUDNN) AND the one you said we can create in any other folder with the name deepface so I did the exact but I am facing this problem..

3.11 won't work. Install 3.10.9 and make it default

**Comment by 6xoxo9** [comment]
I have installed 3.10 version..how do I make this default?

**Comment by 6xoxo9** [comment]
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\deepfake\roop\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\deepfake\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\deepfake\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "D:\deepfake\roop\roop\core.py", line 159, in start
    if predict_video(roop.globals.target_path):
  File "D:\deepfake\roop\roop\predicter.py", line 24, in predict_video
    _, probabilities = opennsfw2.predict_video_frames(video_path=target_path, frame_interval=100)
  File "D:\deepfake\roop\venv\lib\site-packages\opennsfw2\_inference.py", line 114, in predict_video_frames
    model = make_open_nsfw_model(weights_path=weights_path)
  File "D:\deepfake\roop\venv\lib\site-packages\opennsfw2\_model.py", line 200, in make_open_nsfw_model
    model.load_weights(weights_path)
  File "D:\deepfake\roop\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\deepfake\roop\venv\lib\site-packages\keras\saving\legacy\save.py", line 471, in load_weights
    raise ImportError(
ImportError: `load_weights` requires h5py package when loading weights from HDF5. Try installing h5py.

**Comment by FurkanGozukara** [comment]
@6xoxo9 try reinstall looks like failed to download model weights

**Comment by 6xoxo9** [comment]
reinstall what?

**Comment by 6xoxo9** [comment]
(venv) D:\deepfake\roop>pip install h5py
Requirement already satisfied: h5py in d:\deepfake\roop\venv\lib\site-packages (3.9.0)
Requirement already satisfied: numpy>=1.17.3 in d:\deepfake\roop\venv\lib\site-packages (from h5py) (1.23.5)

(venv) D:\deepfake\roop>python run.py --keep-frames --keep-fps --execution-provider cuda
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\deepfake\roop\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\deepfake\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\deepfake\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "D:\deepfake\roop\roop\core.py", line 159, in start
    if predict_video(roop.globals.target_path):
  File "D:\deepfake\roop\roop\predicter.py", line 24, in predict_video
    _, probabilities = opennsfw2.predict_video_frames(video_path=target_path, frame_interval=100)
  File "D:\deepfake\roop\venv\lib\site-packages\opennsfw2\_inference.py", line 114, in predict_video_frames
    model = make_open_nsfw_model(weights_path=weights_path)
  File "D:\deepfake\roop\venv\lib\site-packages\opennsfw2\_model.py", line 200, in make_open_nsfw_model
    model.load_weights(weights_path)
  File "D:\deepfake\roop\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\deepfake\roop\venv\lib\site-packages\keras\saving\legacy\save.py", line 471, in load_weights
    raise ImportError(
ImportError: `load_weights` requires h5py package when loading weights from HDF5. Try installing h5py.

**Comment by FurkanGozukara** [comment]
@6xoxo9 i just did a fresh install

worked flawless. by fresh i mean i installed from 0 latest commit

best i can do is if you become my at least silver patreon i can connect your computer and try to install for you

here my install steps : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/1-Click-DeepFake-Tutorial.md

**Comment by 6xoxo9** [comment]
help man...

**Comment by 6xoxo9** [comment]
when i am saving the video in a folder it only says output not output.mp4..please help

**Comment by 6xoxo9** [comment]
> @6xoxo9 i just did a fresh install
> 
> worked flawless. by fresh i mean i installed from 0 latest commit
> 
> best i can do is if you become my at least silver patreon i can connect your computer and try to install for you
> 
> here my install steps : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/1-Click-DeepFake-Tutorial.md

still not helpful.. this is clear making me go mad from yesterday...does this really work? cause I have followed  every step

**Comment by FurkanGozukara** [comment]
> > @6xoxo9 i just did a fresh install
> > worked flawless. by fresh i mean i installed from 0 latest commit
> > best i can do is if you become my at least silver patreon i can connect your computer and try to install for you
> > here my install steps : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/1-Click-DeepFake-Tutorial.md
> 
> still not helpful.. this is clear making me go mad from yesterday...does this really work? cause I have followed every step

works on my pc but don't know what is the problem on your pc
did you uninstall python and tried to reinstall?

**Comment by 6xoxo9** [comment]
![Screenshot (300)](https://github.com/FurkanGozukara/Stable-Diffusion/assets/138882379/702b0b76-8ce6-4a9b-9369-10cc821aa6c8)
now I'm stuck here

**Comment by FurkanGozukara** [comment]
> ![Screenshot (300)](https://user-images.githubusercontent.com/138882379/251963424-702b0b76-8ce6-4a9b-9369-10cc821aa6c8.png) now I'm stuck here

i think your python installation is the main problem

uninstall python
restart

watch this video 
https://youtu.be/B5U7LJOvH6g

 and install python in my video
then reinstall roop
and let me know results

**Comment by 6xoxo9** [comment]
D:\deepfake\roop>python run.py
1/1 [==============================] - 1s 818ms/step

D:\deepfake\roop>python run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\India/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
100%|█████████████████████████████████████████████████████████████████████████████| 1201/1201 [00:01<00:00, 694.51it/s]

I'm stuck here..can u please guide me? the software roop closes after this and I don't receive any video

**Comment by FurkanGozukara** [comment]
> D:\deepfake\roop>python run.py 1/1 [==============================] - 1s 818ms/step
> 
> D:\deepfake\roop>python run.py Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: C:\Users\India/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: C:\Users\India/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: C:\Users\India/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: C:\Users\India/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: C:\Users\India/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (640, 640) 100%|█████████████████████████████████████████████████████████████████████████████| 1201/1201 [00:01<00:00, 694.51it/s]
> 
> I'm stuck here..can u please guide me? the software roop closes after this and I don't receive any video

i think now you are stuck with not safe for work video - or maybe another video

did you try different videos? at least some should work

you can also test videos i shared on my patreon to verify
