### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [FurkanGozukara/Stable-Diffusion#2]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

CC-BY-SA-4.0 might also be appropriate for this repository.

**Comment by FurkanGozukara** [comment]
> I see you have no LICENSE file for this project. The default is copyright.
> 
> I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.
> 
> CC-BY-SA-4.0 might also be appropriate for this repository.

Thanks how should I add it? Just write to readme?

**Comment by TechnologyClassroom** [comment]
1. In GitHub, start at the repository page.
1. Click on the `Add file` button and select `Create new file`.
1. In the `Name of your file...` text box, type in `LICENSE` and a new button will appear.
1. Click on the `Choose a license template` button.
1. Click on the license that you would like to use.  I would recommend `GNU General Public License v3.0` or `GNU Affero General Public License v3.0`.  A brief description of what the license does will show on the screen.
1. Click on the `Review and Submit` button.
1. Beneath `Commit new file` enter a commit description.  I like to use the precise SPDX identifier for the commit such as `GPL-3.0-or-later` or `AGPL-3.0-or-later`.
1. Click on the `Commit directly to the x branch.` radio button.
1. Click on the `Commit new file` button.

GitHub might have updated the process since I wrote this so let me know if any steps don't work.

**Comment by FurkanGozukara** [comment]
> 5\. GNU General Public License v3.0

i added GNU General Public License v3.0
