### ISSUE TITLE
 After setting the det-size to (640, 640), it reaches 100%, but then it stops.

### ISSUE THREAD

**Issue by karon1015** [FurkanGozukara/Stable-Diffusion#20]
I am running it on Google Colab, and after completing the "git clone" code, when I launch the swap code, it reaches 100% after "set det-size:(640,640)", but then it stops and the "face_changed_video.mp4" is not generated. What should I do to resolve this?

**Comment by FurkanGozukara** [comment]
> 

1st : if your video is not safe for work that is why
2nd : sadly not works with all videos and faces try another one
