### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by aarvndhNG** [FurkanGozukara/Stable-Diffusion#21]
FileNotFoundError: [Errno 2] No such file or directory: 
'/root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-0.9/
refs/main'

**Comment by FurkanGozukara** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-0.9/ refs/main'

Please accept terms and enter your token

**Comment by FurkanGozukara** [comment]
I have runpod auto installer which you don't have enter your token

Just change folder path

Should work on linux
@aarvndhNG

https://www.patreon.com/posts/auto-sdxl-runpod-85845581

**Comment by aarvndhNG** [comment]
> I have runpod auto installer which you don't have enter your token
> 
> Just change folder path
> 
> Should work on linux @aarvndhNG
> 
> https://www.patreon.com/posts/auto-sdxl-runpod-85845581

Yep I do

**Comment by FurkanGozukara** [comment]
> > I have runpod auto installer which you don't have enter your token
> > Just change folder path
> > Should work on linux @aarvndhNG
> > https://www.patreon.com/posts/auto-sdxl-runpod-85845581
> 
> Yep I do

you solved the problem?

**Comment by aarvndhNG** [comment]
No

Couldn't connect to the Hub: 403 Client Error. (Request ID: Root=1-64ad4d3d-267bf78e001ba47258d75f2b;3eff9996-bcea-4314-ba54-506e56449c46)

Cannot access gated repo for url https://huggingface.co/api/models/stabilityai/stable-diffusion-xl-base-0.9.
Access to model stabilityai/stable-diffusion-xl-base-0.9 is restricted and you are not in the authorized list. Visit https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9 to ask for access..
Will try to load from local cache.
Traceback (most recent call last):
  File "/content/stable-diffusion-xl-demo/app6.py", line 36, in <module>
    pipe = DiffusionPipeline.from_pretrained(model_key_base, torch_dtype=torch.float16, use_auth_token=access_token)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 882, in from_pretrained
    cached_folder = cls.download(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1315, in download
    cached_folder = snapshot_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-0.9/refs/main'

**Comment by FurkanGozukara** [comment]
> I got this error

do you have hugging face account?

**Comment by aarvndhNG** [comment]
Yep

**Comment by aarvndhNG** [comment]
Blackwolf2

**Comment by cclcng** [comment]
i got a little closer by deleting the original file from the hub folder in users, and running install.bat again, but asfterwared, when I run.batt it says 
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-64ae3923-52adb9127664b3dd76eee807;bb1d595b-14c6-434d-88b8-5ba03d6624c1)

Repository Not Found for url: https://huggingface.co/api/models/stabilityai/stable-diffusion-xl-base-0.9.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password..
Will try to load from local cache.
Traceback (most recent call last): and 
 File "C:\Users\User\SDXL\stable-diffusion-xl-demo\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\User\SDXL\stable-diffusion-xl-demo\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-xl-base-0.9\\refs\\main'
Press any key to continue . . .

nto sure what is going on .. at all

**Comment by FurkanGozukara** [comment]
> What do I do ?

try again today

show screenshot of your token and setup and everything

you can delete token later it is fine
