### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement xformers==0.0.21.dev564

### ISSUE THREAD

**Issue by imdevine** [FurkanGozukara/Stable-Diffusion#22]
The problem started to occur today:
ERROR: Could not find a version that satisfies the requirement xformers==0.0.21.dev564 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21.dev569, 0.0.21.dev571)
ERROR: No matching distribution found for xformers==0.0.21.dev564

All huggingface model permissions are granted,

**Comment by anuroop18** [comment]
In requiremants3.txt, change 
xformers==0.0.21.dev564   to    xformers==0.0.20

**Comment by FurkanGozukara** [comment]
> The problem started to occur today: ERROR: Could not find a version that satisfies the requirement xformers==0.0.21.dev564 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21.dev569, 0.0.21.dev571) ERROR: No matching distribution found for xformers==0.0.21.dev564
> 
> All huggingface model permissions are granted,

thanks a lot just updated to the latest version 0.0.21.dev571
