### ISSUE TITLE
How much VRAM you need to train SDXL LoRA with Kohya  GUI?

### ISSUE THREAD

**Issue by julscloudops** [FurkanGozukara/Stable-Diffusion#24]
Hello Furkan, thank you for your hard work. 

How much VRAM you need to train locally SDXL LoRA with Kohya GUI? Is there an available Google Collab notebook to accomplish this? 

Kind regards

**Comment by FurkanGozukara** [comment]
> Hello Furkan, thank you for your hard work.
> 
> How much VRAM you need to train locally SDXL LoRA with Kohya GUI? Is there an available Google Collab notebook to accomplish this?
> 
> Kind regards

I plan to prepare colab hopefully soon

I was able to train with 12gb and network rank 64

Posted settings  on patreon hopefully will make a new tutorial for that

**Comment by FurkanGozukara** [comment]
tutorial arrived for 12 gb vram

hopefully google colab tutorial coming soon : https://youtu.be/sBFGitIvD2A
