### ISSUE TITLE
Finish / Start of AutoInst on Runpod not possible

### ISSUE THREAD

**Issue by El-Sonador** [FurkanGozukara/Stable-Diffusion#28]
Hi, and first of all, thank you a lot for your work and explanation!

Worked at Runpod, RTX A6000 like you described in your youtube auto install video.

And every think worked fine till i executed:
   cd /workspace/stable-diffusion-xl-demo
   source venv/bin/activate
   PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256 SHARE=true ENABLE_REFINER=true python app7.py

Here i got several warnings as a feedback (see below what i reproduced when started again)
Interestingly it gives me a 127. ip to start.
- when i click the 127, there is nothing - as i expected
- wenn i start the web terminal and connect to web terminal, i get only this:  "root@38f87f9b1020:/workspace#" on a black page.
- When i click connect to HTTP... Port3001, i get the 502 Page

Thanks for the support
El

----------------------------------------
root@38f87f9b1020:/workspace/stable-diffusion-xl-demo# cd /workspace/stable-diffusion-xl-demo
source venv/bin/activate
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256 SHARE=true ENABLE_REFINER=true python app7.py
Loading model /workspace/stable-diffusion-xl-base-0.9
Loading pipeline components...:  29%|█████████████████████████████████████▋                                                                                              | 2/7 [0Loading pipeline components...:  43%|████████████████████████████████████████████████████████▌                                                                           | 3/7 [0Loading pipeline components...:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 6/7 [0Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:32<00:00,  4.62s/it]
Loading model /workspace/stable-diffusion-xl-refiner-0.9
Loading pipeline components...: 100%|█| 5/5 [00:11<00:00,  
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Blocks, please remove them: {'timeout': 300}
  warnings.warn(
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/layouts.py:75: UserWarning: mobile_collapse is no longer supported.
  warnings.warn("mobile_collapse is no longer supported.")
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/components.py:198: UserWarning: 'rounded' styling is no longer supported. To round adjacent components together, place them in a Column(variant='box').
  warnings.warn(
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/components.py:216: UserWarning: 'border' styling is no longer supported. To place adjacent components in a shared border, place them in a Column(variant='box').
  warnings.warn(
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/components.py:207: UserWarning: 'margin' styling is no longer supported. To place adjacent components together without margin, place them in a Column(variant='box').
  warnings.warn(
/workspace/stable-diffusion-xl-demo/venv/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'enabled': True}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

**Comment by FurkanGozukara** [comment]
@El-Sonador sorry for delay
i am still testing will let you know soon

**Comment by FurkanGozukara** [comment]
@El-Sonador 
I have updated the auto installer

Make sure that your container disk size is at least 30 GB

volume disk size is not anymore important

use latest script from here

https://www.patreon.com/posts/85845581

it will give you gradio share link after run use it

**Comment by El-Sonador** [comment]
Hi Furkan,
thanks a lot for the fast support ! ! ! Thats extraordinary! 
Testing it at the moment.

What does "volume disk size is not anymore important" mean? Can i stick with 75?
This would dramatically decrease the standby price and would be highly appreciated.

**Comment by FurkanGozukara** [comment]
> Hi Furkan, thanks a lot for the fast support ! ! ! Thats extraordinary! Testing it at the moment.
> 
> What does "volume disk size is not anymore important" mean? Can i stick with 75? This would dramatically decrease the standby price and would be highly appreciated.

yes you can even use 50 gb 

it will load models into container disk with minimal amount

**Comment by El-Sonador** [comment]
Wow, great improvement! 👍 
But actually i will stay with 1.5. After testing XL, it feels like a very limited Demo version of 1.5. There are so much functions missing (or more realistically, just did not found them yet).  😄

**Comment by FurkanGozukara** [comment]
> Wow, great improvement! 👍 But actually i will stay with 1.5. After testing XL, it feels like a very limited Demo version of 1.5. There are so much functions missing (or more realistically, just did not found them yet). 😄

ye it is getting better over time

**Comment by El-Sonador** [comment]
:) hope so. Will close this, sine you solved it. thank you.
