### ISSUE TITLE
No module named 'opennsfw2'

### ISSUE THREAD

**Issue by pixelsncodes** [FurkanGozukara/Stable-Diffusion#3]
Getting this error when trying to execute 
(venv) D:\Deepface\roop>python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from roop import core
  File "D:\Deepface\roop\roop\core.py", line 15, in <module>
    from opennsfw2 import predict_video_frames, predict_image
ModuleNotFoundError: No module named 'opennsfw2'

How do I fix it?

**Comment by FurkanGozukara** [comment]
@pixelsncodes this happens when c++ tools are not installed

have you installed them?

if you have installed which packages did you select and install?

**Comment by FurkanGozukara** [comment]
> I have the same error, installed C++ tools 2022 17.6.2 but it's an app which allows the installation of several package, once the gui of c++ tools i don't know if i must install something in it too ?

if not working yes install all packages
