### ISSUE TITLE
No module named "onnxruntime"

### ISSUE THREAD

**Issue by swapper69** [FurkanGozukara/Stable-Diffusion#36]
![onnxruntime error](https://github.com/FurkanGozukara/Stable-Diffusion/assets/152629636/4db7d923-5581-472b-855a-267203f49a46)

Hi,

I get stuck on this step with the following error - No module named "onnxruntime"

**Step 8 : inswapper_128 model file
You don't need to download inswapper_128 manually anymore**

https://youtu.be/OI1LEN-SgLM?si=NzlOJsTUmvBZPHoS
Have followed the tutorial here.

**Comment by FurkanGozukara** [comment]
@swapper69 you need to have c++ accurately installed. otherwise you will get that error because during install it will fail to install and compile onnxruntime libraries

**Comment by swapper69** [comment]
Okay, shall check again. Thanks

**Comment by swapper69** [comment]
https://huggingface.co/OwlMaster/gg/resolve/main/inswapper_128.onnx

Since this file is not available to download, can this be the reason for the above error!

**Comment by swapper69** [comment]
![c++](https://github.com/FurkanGozukara/Stable-Diffusion/assets/152629636/b8db618a-5f4c-4251-b129-d2c4503b2335)

It shows the installations are up to date!

**Comment by swapper69** [comment]
![collab](https://github.com/FurkanGozukara/Stable-Diffusion/assets/152629636/31cc5cfe-8899-4ffc-854c-394f22a6c8f4)

run.py: error: unrecognized arguments: -f face1.png --gpu

Error while trying with Collab!

**Comment by FurkanGozukara** [comment]
> ![collab](https://private-user-images.githubusercontent.com/152629636/287719626-31cc5cfe-8899-4ffc-854c-394f22a6c8f4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTg2MjksIm5iZiI6MTcwMTY5ODMyOSwicGF0aCI6Ii8xNTI2Mjk2MzYvMjg3NzE5NjI2LTMxY2M1Y2ZlLTg4OTktNGZmYy04NTRjLTM5NGYyMmE2YzhmNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxMzU4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2ZkN2QzNmE2OGU0YTA0NDlkOWNjOWEyZjc4NGY4NWE4ODJiODg1YTk4YTM2MmM1ZDU0MTE5YTA3ZDlmNjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TtWBZ3q8SA9dwS9R4gNTYi0-c5iRDCB-NZUBh9Dbss8)
> 
> run.py: error: unrecognized arguments: -f face1.png --gpu
> 
> Error while trying with Collab!

that is wrong use latest colab

https://colab.research.google.com/github/FurkanGozukara/Stable-Diffusion/blob/main/ColabNotebooks/1_click_deep_fake_for_free_by_SECourses.ipynb

**Comment by swapper69** [comment]
run.py: error: unrecognized arguments: -f face1.png --gpu

Still ran into the same error with the above link!

**Comment by FurkanGozukara** [comment]
> run.py: error: unrecognized arguments: -f face1.png --gpu
> 
> Still ran into the same error with the above link!

you are not reading the file

the run command changed

read the file

**Comment by swapper69** [comment]
Got it.
Thanks a lot
