### ISSUE TITLE
Kohya LoRA - Kaggle

### ISSUE THREAD

**Issue by alan741963** [FurkanGozukara/Stable-Diffusion#44]
When I want to enter the GUI through ngrok, the screen displays "ERR_NGROK_8012", Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at localhost:7860. The error encountered was:dial tcp 127.0 .0.1:7860: connect: connection refused

**Comment by FurkanGozukara** [comment]
> When I want to enter the GUI through ngrok, the screen displays "ERR_NGROK_8012", Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at localhost:7860. The error encountered was:dial tcp 127.0 .0.1:7860: connect: connection refused

you can ignore it. just dont miss the steps

first generate link

open link but dont click the visit site button

start web ui

then click visit site button

if you record a video and send me i can check and verify your steps

**Comment by alan741963** [comment]
Where can I start web ui ?

**Comment by FurkanGozukara** [comment]
> Where can I start web ui ?

did you see this latest video?

https://youtu.be/16-b1AjvyBE

**Comment by alan741963** [comment]
yes

**Comment by alan741963** [comment]
I successfully made a checkpoint model, but when I tried to make LORA for the second time, I couldn’t connect it.

**Comment by FurkanGozukara** [comment]
> I successfully made a checkpoint model, but when I tried to make LORA for the second time, I couldn’t connect it.

yes for second time repeat the first time process and it will work. ignore error messages

**Comment by alan741963** [comment]
I understand, thank you very much
