### ISSUE TITLE
Using another model

### ISSUE THREAD

**Issue by coder8x** [FurkanGozukara/Stable-Diffusion#50]
Thanks for the colab, it works fine but it can't let you decide which model to use

**Comment by coder8x** [comment]
with comfy you can

**Comment by FurkanGozukara** [comment]
hello which one please link me

**Comment by coder8x** [comment]
Hey! The Stable_Diffusion_SDXL_on_Google_Colab, it works but the model is not that great, i noticed other colabs have the option to download or select from google drive, fast stable diffusion for example-

**Comment by FurkanGozukara** [comment]
> Hey! The Stable_Diffusion_SDXL_on_Google_Colab, it works but the model is not that great, i noticed other colabs have the option to download from civitai or select from google drive, fast stable diffusion for example, would be a cool feature to add

Watch this tutorial and you will have even faster way to download after saving into hugging face

https://youtu.be/X5WVZ0NMaTg?si=9E63cWSY_zeYOL_L

Also if you need best quality colab not gonna give you that

Use either one trainer or kohya

**Comment by coder8x** [comment]
I know how to download models, "If you need best quality colab not gonna give you that" is the only reasonable part of your response.
