### ISSUE TITLE
No such file or directory: '/content/roop'

### ISSUE THREAD

**Issue by BhadurAli** [FurkanGozukara/Stable-Diffusion#52]
Hey!
when I tried to run it will give me thiss error. 
[Errno 2] No such file or directory: '/content/roop'
/content
python3: can't open file '/content/run.py': [Errno 2] No such file or directory

first it is running as expected but from past one day it is giving me some odd behaviour and can't run properly. I thing it is because of an update or something?

**Comment by FurkanGozukara** [comment]
I suggest use rope pearl much better

https://youtu.be/RdWKOUlenaY?si=1kE_BvbeCnb_uUrj

**Comment by BhadurAli** [comment]
That's awesome.
I am happy to use this. But can you replace this version to one previous
version, that version is working fine but after update it is giving error

**Comment by FurkanGozukara** [comment]
This version still works you are just doing it wrong

I will test colab today and let you know but it is working tested few weeks ago last time

**Comment by BhadurAli** [comment]
You are right. The script is working but it is not changing the face.I
already swap the face for so many times before but when I do this after the
6 june update the script is running but it does not swap the face. I use
the same video as a reference with the same image when I do before the 6
june update. It is giving the expected result but now it is giving me the
same original video as output. See the attached picture as reference. So I
kindly request you to please revert the changes to the same script as it
was before 6 june update

**Comment by BhadurAli** [comment]
Hey!
Did you understand what I am saying please help me😔
