### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by Rahul-techy** [FurkanGozukara/Stable-Diffusion#53]
onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory.

**Comment by FurkanGozukara** [comment]
hello you need to have accurate c++ tools and cuda 11.8

please watch this video without skip and apply all

https://youtu.be/-NjNy7afOQ0 

@Rahul-techy

**Comment by Rahul-techy** [comment]
Thanks for prompt reply but i forgot to mention i was using deepfake stable diffusion  notebook on google colab so all download links are predefined in the notebook itself . Just before 3-4 days problem started now after giving up img and video path this eroor shows up and all command turns red as well as video process goes too slow even for 6-7 sec video it taking more than a hour. So i think notebook need some adjustment so on colab it works like it use to work few days before. Thanks.

**Comment by FurkanGozukara** [comment]
@Rahul-techy just updated and fixed colab

if it asks you restart session dont do that

**Comment by Rahul-techy** [comment]
Thanks for your precious time and rectification of my issues. Now its working fine without any errors. Kuddos for your time response and effort☺️.
